import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABB/d6O2Aw
FMttKl/bu0YihCAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIHuL5rx0/ICfnz0f
/IJay+/V+njAnACVB/AQV99sYMhZAAAAkIiYOWBrTWLRE1c02gToaIMAfV1/PaG9E9oZ9p
Mu5sryo27m0h27M2nRGGJ4EWnC9mnwEay7UVP/qK9O3UZoxrIRQK7j+UTq+PmuplbR25zt
MISYxGLIdOiz/TeCzRTyAggnHTTBqcI3cy77IcZWgZK9YcW04ammxpsOP0NmpQzW2rh3f6
H+oAAHPrjRQqzTRA==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
