import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACB5QQbZmvEXgw7moFmWM87FolBHLXUAtRhlOu4QnCM0VAAAAJDGFTWKxhU1
igAAAAtzc2gtZWQyNTUxOQAAACB5QQbZmvEXgw7moFmWM87FolBHLXUAtRhlOu4QnCM0VA
AAAEBixWktKOzBzDsl7bzzFaZOVB6oa/pi013dM57q+y2X0XlBBtma8ReDDuagWZYzzsWi
UEctdQC1GGU67hCcIzRUAAAABm15LWtleQECAwQFBgc=
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
